<?php

namespace KikCMS\Services\Util;


use DateInterval;
use DateTime;
use KikCMS\Classes\Translator;
use Phalcon\Di\Injectable;

/**
 * Utility Service for handling DateTime objects
 *
 * @property Translator $translator
 */
class DateTimeService extends Injectable
{
    /**
     * Convert a datetime string, generated by a datepicker, to DateTime
     *
     * @param string $dateTime
     * @return null|DateTime
     */
    public function getFromDatePickerValue(?string $dateTime): ?DateTime
    {
        if ( ! $dateTime) {
            return null;
        }

        return DateTime::createFromFormat($this->getDateFormat(), $dateTime);
    }

    /**
     * Get the date one year ago, with the first day of that month
     *
     * @return DateTime
     */
    public function getOneYearAgoFirstDayOfMonth(): DateTime
    {
        $dateTime     = (new DateTime())->sub(new DateInterval('P1Y'));
        $subtractDays = (int) $dateTime->format('d') - 1;

        $dateTime->sub(new DateInterval('P' . $subtractDays . 'D'));

        return $dateTime;
    }

    /**
     * Get the default date format for the current language
     *
     * @return string
     */
    private function getDateFormat(): string
    {
        return $this->translator->tl('system.phpDateFormat');
    }
}