version: "3"
services:
  mysql:
    image: mariadb:10.6.18
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${PASS}
    volumes:
      - ~/.docker-kikdev/mysql/:/var/lib/mysql
    networks:
      kikdev:
        aliases:
          - mysql

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      kikdev:
        aliases:
          - mail

networks:
  kikdev:
    external:
      name: kikdev