version: "3"
services:
  php:
    build: ./../../../../../DockerKikDev/DockerfilePhalcon4
    restart: always
    ports:
      - "${SITE_PORT}:443"
    volumes:
      - ../../../../public_html/:/var/www/html:cached
      - ../../../../:/var/www:cached
      - ../../:/var/www/vendor/kiksaus:cached
      - ~/.docker-kikdev/logs:/var/log/apache2/:cached
      #the following dirs are excluded for speed and stability
      - /var/www/assets/
      - /var/www/.git/
      - /var/www/vendor/kiksaus/kikcms/assets/
    networks:
      kikdev:
        aliases:
          - ${SITE_ALIAS}
    environment:
      XDEBUG_CONFIG: remote_host=docker.for.mac.host.internal

networks:
  kikdev:
    external:
      name: kikdev